
//Kafras
npc: npc/import/kafras/functions_kafras.txt
npc: npc/import/kafras/kafras.txt

//Premium buff
npc: npc/import/premium buff/Account_buff.txt
npc: npc/import/premium buff/Catstorage.txt

//PC Cafe
npc: npc/import/pc cafe/pc_cafe.txt
npc: npc/import/pc cafe/goldpc.txt

//itemmall
npc: npc/import/other/gympass.txt
npc: npc/re/import/merchants/cashmall.txt
npc: npc/re/import/merchants/enchan_upg.txt
npc: npc/re/import/merchants/rgsr_in.txt
npc: npc/re/import/merchants/shadow_refiner.txt
npc: npc/re/import/other/Fallen_Angel_Wing.txt
npc: npc/re/import/other/item_merge.txt
npc: npc/re/import/other/Midgear_Piercing.txt
npc: npc/re/import/other/reset_stat.txt
npc: npc/re/import/other/rwc_enchant.txt

//stylist
npc: npc/re/import/merchants/Extended_Stylist.txt