
//Global
npc: npc/re/import/other/global_npcs.txt
npc: npc/re/import/other/Global_Functions.txt
npc: npc/re/import/other/Global_Functions_custom.txt

//cities

npc: npc/re/import/cities/izlude.txt
npc: npc/re/import/cities/malangdo.txt

//jobs
npc: npc/re/import/jobs/1-1/swordman.txt
npc: npc/re/import/jobs/novice/academy.txt

//custom
npc: npc/re/import/custom/lasagna/lasagna_npcs.txt

//guides
npc: npc/re/import/guides/navigation.txt
npc: npc/re/import/guides/guides_izlude.txt
npc: npc/re/import/guides/guides_malangdo.txt

//kafras
npc: npc/re/import/kafras/cool_event_corp.txt
npc: npc/re/import/kafras/Kafra_Teleportation_Services.txt
npc: npc/re/import/kafras/kafras.txt
npc: npc/re/import/kafras/Zonda_Teleportation_Services.txt

//merchants
npc: npc/re/import/merchants/3rd_trader.txt
npc: npc/re/import/merchants/advanced_refiner.txt
npc: npc/re/import/merchants/ammo_boxes.txt
npc: npc/re/import/merchants/card_separation.txt
npc: npc/re/import/merchants/cashmall.txt
npc: npc/re/import/merchants/catalog.txt
npc: npc/re/import/merchants/coin_exchange.txt
npc: npc/re/import/merchants/Dealer_Update.txt
npc: npc/re/import/merchants/eden_market.txt
npc: npc/re/import/merchants/Emperium_Seller.txt
npc: npc/re/import/merchants/enchan_illusion_dungeons.txt
npc: npc/re/import/merchants/enchan_mal.txt
npc: npc/re/import/merchants/enchan_rockridge.txt
npc: npc/re/import/merchants/enchan_upg.txt
npc: npc/re/import/merchants/enchan_verus.txt
npc: npc/re/import/merchants/enchantgrade.txt
npc: npc/re/import/merchants/Extended_Stylist.txt
npc: npc/re/import/merchants/hd_refiner.txt
npc: npc/re/import/merchants/malangdo_costume.txt
npc: npc/re/import/merchants/mysterious_cookie_shop.txt
npc: npc/re/import/merchants/nightmare_biolab.txt
npc: npc/re/import/merchants/novice_vending_machine.txt
npc: npc/re/import/merchants/pet_groomer.txt
npc: npc/re/import/merchants/quests_exp_175.txt
npc: npc/re/import/merchants/refine.txt
npc: npc/re/import/merchants/rgsr_in.txt
npc: npc/re/import/merchants/shadow_refiner.txt
npc: npc/re/import/merchants/ticket_refiner.txt

//other
npc: npc/re/import/other/Fallen_Angel_Wing.txt
npc: npc/re/import/other/item_merge.txt
npc: npc/re/import/other/mercenary_rent.txt
npc: npc/re/import/other/Midgear_Piercing.txt
npc: npc/re/import/other/reset_stat.txt
npc: npc/re/import/other/resetskill.txt
npc: npc/re/import/other/rwc_enchant.txt

//PC Cafe
npc: npc/re/import/pc cafe/goldpc.txt
npc: npc/re/import/pc cafe/pc_cafe.txt

//Premium buff
npc: npc/re/import/premium buff/Account_buff.txt
npc: npc/re/import/premium buff/Catstorage.txt

//quests
//--------eden----------
npc: npc/re/import/quests/eden/1-39.txt
npc: npc/re/import/quests/eden/40-69.txt
npc: npc/re/import/quests/eden/70-99.txt
npc: npc/re/import/quests/eden/100-110.txt
npc: npc/re/import/quests/eden/120-140.txt
npc: npc/re/import/quests/eden/130-190.txt
npc: npc/re/import/quests/eden/champions.txt
npc: npc/re/import/quests/eden/eden_common.txt
npc: npc/re/import/quests/eden/eden_quests.txt
//--------eden----------
npc: npc/re/import/quests/Critura quest.txt
npc: npc/re/import/quests/HelpMeShorty.txt
npc: npc/re/import/quests/mrsmile.txt
npc: npc/re/import/quests/quests_13_1.txt
npc: npc/re/import/quests/quests_17_2.txt
npc: npc/re/import/quests/quests_dicastes.txt
npc: npc/re/import/quests/quests_dungeons_200.txt
npc: npc/re/import/quests/quests_lighthalzen.txt
npc: npc/re/import/quests/quests_malangdo.txt

//warps
npc: npc/re/import/warps/cities/izlude.txt
npc: npc/re/import/warps/other/TrainingZone.txt