// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Script Commands
 * Place the definition of custom script commands in this file.
 * Format:
 *	BUILDIN_DEF(command_name,"parameters"),
 **/

//BUILDIN_DEF(example,""),

//-----------------------------------------------------
//Custom bonuses start
//-----------------------------------------------------
BUILDIN_DEF(exbonus,"sii??"),
BUILDIN_DEF(getequipcombocnt,""),
BUILDIN_DEF(clonemob,"siisi??????"),
BUILDIN_DEF2(bonus,"bonus7","ivviiiii"),
//-----------------------------------------------------
//Custom bonuses end
//-----------------------------------------------------
