
//Kafras
npc: npc/import/kafras/functions_kafras.txt
npc: npc/import/kafras/kafras.txt

//Premium buff
npc: npc/import/premium buff/Account_buff.txt
npc: npc/import/premium buff/Catstorage.txt

//PC Cafe
npc: npc/import/pc cafe/pc_cafe.txt
npc: npc/import/pc cafe/goldpc.txt