
npc: npc/import/other/CashShop_Functions_custom.txt

//cities
npc: npc/import/cities/alberta.txt
npc: npc/import/cities/izlude.txt

//jobs
npc: npc/import/jobs/1-1e/gunslinger.txt

//kafras
npc: npc/import/kafras/functions_kafras.txt
npc: npc/import/kafras/kafras.txt

//merchants
npc: npc/import/merchants/refine.txt

//other
npc: npc/import/other/gympass.txt
npc: npc/import/other/mercenary_rent.txt

//quests
npc: npc/import/quests/gunslinger_quests.txt
npc: npc/import/quests/mrsmile.txt
npc: npc/import/quests/quests_13_1.txt